#!/bin/bash

unset GIT_DIR

echo "Post Recieve"

#source the correct environment
source /usr/local/pythonenv/gibthon-env/bin/activate

# install requirements
pip install -r deployment/requirements.pip

#gather static files
python gibthon/manage.py collectstatic --noinput

#apply south migrations
python gibthon/manage.py migrate gibson
python gibthon/manage.py migrate fragment
python gibthon/manage.py migrate accounts

#restore apache config
cp deployment/apache/httpd.conf.production ../httpd.conf

su --session-command="/sbin/httpd -k restart" root

