#!/bin/bash

echo "Post Recieve"


# install requirements

cd ..
pip-python install -r deployment/requirements.pip

#gather static files

#apply south migrations

#restore apache config
sudo cp deployment/apache/httpd.conf.production /etc/httpd/conf.d/gibthon.conf

sudo service httpd restart

